services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: observability-otel
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/otel-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped