from google.adk.tools import FunctionTool
from ..models import WorkflowData

_memory_store: dict[str, WorkflowData] = {}


def save_workflow(
    task: str,
    plan: str,
    execution_plan: list[str],
) -> str:
    """
    Create and store a workflow in memory.

    Args:
        task: User's task.
        plan: High-level plan generated by the planner.
        execution_plan: Ordered list of execution steps.

    Returns:
        Confirmation message.
    """

    workflow = WorkflowData(
        task=task,
        plan=plan,
        execution_plan=execution_plan,
    )

    _memory_store[task] = workflow

    return (
        f"Workflow saved successfully.\n"
        f"Task: {task}\n"
        f"Steps: {len(execution_plan)}"
    )


def load_workflow(task: str) -> str:
    """
    Retrieve a previously saved workflow.

    Args:
        task: Task identifier.

    Returns:
        Workflow summary or an informative message if not found.
    """

    workflow = _memory_store.get(task)

    if workflow is None:
        return f"No workflow found for task: '{task}'."

    return f"""
Task:
{workflow.task}

Plan:
{workflow.plan}

Execution Plan:
{chr(10).join(f"- {step}" for step in workflow.execution_plan)}
"""


save_workflow_tool = FunctionTool(func=save_workflow)
load_workflow_tool = FunctionTool(func=load_workflow)