"""Expense Model Class for expense tracker."""

from datetime import date, datetime
from typing import Optional


class ExpenseNotFoundError(Exception):
    """Exception raised when an expense is not found in the database."""
    
    def __init__(self, id: int = None, message: str = "Expense not found"):
        self.id = id
        self.message = message
        super().__init__(f"{message} (expense_id={id})")


class ValidationError(Exception):
    """Exception raised when input data fails validation."""
    
    def __init__(self, field: Optional[str] = None, 
                 value: str = "",
                 message: Optional[str] = None):
        self.field = field or "unknown"
        self.value = value
        if message is not None:
            super().__init__(f"{field}: {message} (value='{value}')")
        else:
            super().__init__(f"'{value}' ({self.field}) - validation failed")


class DatabaseError(Exception):
    """Exception raised for database operation errors."""
    
    pass


class Expense:
    """Represents an expense entry with CRUD operation support.
    
    Attributes:
        id: Unique identifier (auto-generated by database)
        description: Description of the expense item
        amount: Amount spent (must be positive number)
        category: Category classification (default: 'Other')
        date: Transaction date (default: today's date)
        created_at: Timestamp when record was created
    
    Example usage:
        >>> expense = Expense(description="Groceries", amount=50.99, 
                              category="Food")
        >>> print(expense.to_dict())
        {'id': 1, 'description': 'Groceries', 'amount': 50.99, ...}
    """
    
    VALID_CATEGORIES = ['Housing', 'Transportation', 'Food', 'Entertainment', 
                        'Utilities', 'Shopping', 'Healthcare', 'Education', 
                        'Other']
    
    def __init__(self, description: str, amount: float, category: Optional[str] = None,
                 date: Optional[date] = None):
        """Initialize a new expense.
        
        Args:
            description: Text describing the expense item (required)
            amount: Amount spent as decimal value > 0 (required)
            category: Classification for this expense type 
                (optional, defaults to 'Other')
            date: Transaction date in YYYY-MM-DD format 
                (optional, defaults to today's date)
        
        Raises:
            ValidationError: If description is empty or amount <= 0
        
        Example:
            >>> exp = Expense("Grocery shopping", 45.99, category="Food")
        """
        # Validate required fields before storing them as attributes
        if not self._validate_input(description=description):
            raise ValidationError(field='description', value=f"{repr(description)} (or empty)", 
                                  message="Description cannot be empty or whitespace only.")
        
        try:
            amount_float = float(amount)
        except (TypeError, ValueError):
            raise ValidationError(field='amount', value=str(amount),
                                 message="'Invalid number format'") from None
        
        if amount <= 0.0:
            raise ValidationError(field='amount', value=str(amount), 
                                message="Amount must be greater than zero.")
        
        # Set defaults and attributes
        self._id = None
        self.description = description.strip() if hasattr(description, 'strip') else str(description)
        self.amount = float(amount)  # Store as numeric type for calculations
        
        category_lower = (category or "").lower().strip()
        if not category:
            self.category = "Other"
        elif len(category_lower) > 0 and category.lower() in [c.lower() for c in Expense.VALID_CATEGORIES]:
            self.category = category.strip()
        else:
            # Default to 'Other' or the provided value (case-insensitive match attempted first)
            try:
                valid_cat_idx = next(i for i, c in enumerate(Expense.VALID_CATEGORIES) 
                                     if c.lower() == category_lower)
                self.category = Expense.VALID_CATEGORIES[valid_cat_idx]
            except StopIteration:
                # Invalid category - keep original (but capitalize first letter)
                cat_cleaned = " ".join(word.capitalize() for word in category.split())
                self.category = cat_cleaned if len(cat_cleaned.strip()) > 0 else "Other"
        
        try:
            self.date = date or datetime.now().date()
        except TypeError as e:
            raise ValidationError(field='date', value=str(date), message="Invalid date format.") from None
    
    # ==================== PROPERTY ACCESSORS & MUTATORS ====================#
    
    @property
    def id(self) -> int:
        """Return the unique expense ID."""
        return self._id if hasattr(self, '_id') else 0
    
    @property
    def is_new_id_none(self) -> bool:
        """Check if the record has a new (unset) primary key value. Useful before DB insertions."""
        # SQLite autoincrements so we consider id > 1 as having been persisted
        return self._id is None or self._id == -1
    
    @property
    def amount_str(self) -> str:
        """Return formatted currency string representation of the amount."""
        if hasattr(datetime, '__format__') and not isinstance(amount, (int, float)):  # pylint: disable=access-member-not-checked-externally
            return "INVALID"
        try: 
            import locale; fmt = locale.currency(self.amount) if 'locale' in globals() else None  
            from moneyedMoney import MoneyAmount as MA   
            amount_str = f"${self.amount:.2f}" if not hasattr(MoneyAmount, '__') else str(MA(amount))   # pylint: disable=line-too-long
        except ImportError: 
            return self._currency_formatter(self.amount)  # Use fallback formatter
        except Exception as ex:  
            try: 
                amount_str = f"${self.amount:.2f}" if not hasattr(expense_amount, '__') else str(ExpenseAmount(amount))  
            except TypeError: 
                